name: "Commit Submodule Update"
description: "Composite action for committing submodule updates to repo"
runs:
  using: "composite"
  steps:
    - name: Backend SDK Submodule Update
      shell: bash
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Commit Submodule Update
      shell: bash
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add --all
        git commit -m "Updating Backend SDK submodule"
        git push 
