name: Update All Services Repo

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  CHATROOM_SERVICE_REPO: SE-Exort/InfoGrep-ChatroomService
  FM_SERVICE_REPO: SE-Exort/InfoGrep-FileManagementService
  AI_SERVICE_REPO: SE-Exort/InfoGrep-AIService
  AUTH_SERVICE_REPO: SE-Exort/InfoGrep-AuthenticationService

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  auth-service-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.CI_TOKEN }}
          repository: ${{ env.AUTH_SERVICE_REPO }}
      - name: Backend SDK Submodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit Submodule Update
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Updating Backend SDK submodule"
          git push
  
  chatroom-service-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.CI_TOKEN }}
          repository: ${{ env.CHATROOM_SERVICE_REPO }}
      - name: Backend SDK Submodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit Submodule Update
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Updating Backend SDK submodule"
          git push

  file-management-service-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.CI_TOKEN }}
          repository: ${{ env.FM_SERVICE_REPO }}
      - name: Backend SDK Submodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit Submodule Update
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Updating Backend SDK submodule"
          git push

  ai-service-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.CI_TOKEN }}
          repository: ${{ env.AI_SERVICE_REPO }}
      - name: Backend SDK Submodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit Submodule Update
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Updating Backend SDK submodule"
          git push